config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message
	before_action :find_comment, except: [:create]
	before_action :authenticate_user!, except: [:index ,:show]

	def new
		@comment = Comment.new()

	end
	def create
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render:new
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render:edit
		end

	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	def show

	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_message
		@message = Message.find(params[:message_id])
	end
	def find_comment
		@comment = @message.comments.find(params[:id])

	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit , :destroy, :update]
	before_action :authenticate_user!, except: [:index ,:show]
	def index
		@messages = Message.all

	end
	def new 
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to messages_path
		else
			render:new
		end

	end
	def edit

	end

	def update
		@message = Message.find(params[:id])
		if @message.update(message_params) 
			redirect_to messages_path
		else
			render:edit
		end
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		redirect_to messages_path
	end

	def show
	end

	private

		def message_params
			params.require(:message).permit(:title,:description)
		end

		def find_message
		@message = Message.find(params[:id])

		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content.capitalize() %></p>
<p><h4><b>Posted by <%= comment.user.email %><%= time_ago_in_words(comment.created_at) %>ago</h4></b></p>
	

<% if user_signed_in?%>
	<% if @message.user_id == current_user.id %>

		<%= link_to "Edit Comment", edit_message_comment_path(comment.message , comment),class: "btn btn-outline btn-info"%>

		<%= button_to "Delete", message_comment_path(comment.message , comment), method: 'delete', data: { confirm: "Are you sure" },class: "btn btn-danger"%>
	<% end %>
<% end %>

app/views/comments/_form.html.erb



<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">
    	<%= simple_form_for ([@message, @message.comments.build]) do |f| %>
			<%= f.input :content, label: "Content"%>
			<%= f.button :submit %>
		<% end%>
    </p>
  </div>
</div>

app/views/comments/edit.html.erb
<%= simple_form_for([@message, @comment]) do |f|%>
	<%= f.input :content , label: "Content"%>
	<%= f.button :submit%>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="/">Message Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    

      
 

      <% if user_signed_in? %>
        <li><%= link_to "New Messsage", new_message_path, class: "nav-link btn btn-outline  my-2 my-sm-3"%></li>
        <li><%= button_to "Sign Out", destroy_user_session_path, method:'delete' ,class: "nav-link btn btn-outline my-2 my-sm-3"%></li>
      <% else %>
        <li class="nav-item active">
        <%= link_to "Sign Up", new_user_registration_path , class: "nav-link  my-2 my-sm-3"%>
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      </li>
        <li><%= link_to "Log In", new_user_session_path,class: "nav-link  my-2 my-sm-3"%></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>MessageApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

          <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>



  </head>

  <body>
    <%= render "layouts/header"%>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title , lable: "Message Title"%>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<%= render "form"%>

app/views/messages/index.html.erb
<center><br/>



<div class="card" style="width: 100rem;">
  <ul class="list-group list-group-flush">
  	<li class="list-group-item"><h1>Index</h1></li>
    <li class="list-group-item">

		<% @messages.each do |m| %>

				<div class="card text-center">
 				<div class="card-header">
						<h3><strong>Title: <%= m.title%></strong></h3><br/>
  				</div>
  				<div class="card-body">
    				<h5 class="card-title"><%= link_to "View Message", message_path(m),class: "btn-sm btn-secondary" %><br></h5>
  				</div>
				</div>
		<% end %>

    </li>
  </ul>
  <div class="card-footer">
		<%= link_to "New Messsage", new_message_path, class:"btn btn-lg btn-primary"%>  </div>
</div>

</center>



app/views/messages/new.html.erb
<h1>new message</h1>
<%= render "form", message:@message%>

app/views/messages/show.html.erb
<div class="container mg-2">
	<div class="jumbotron jumbotron-fluid">
	  <div class="container">
	    <h1 class="display-4"><strong><%= @message.title %></strong></h1>
   		  <hr class="my-4">

	    <p class="lead">
		<p>Posted by <%= @message.user.email %><%= time_ago_in_words(@message.created_at) %>ago</p>

		<br/>
		<h3>
		<%= @message.description %></h3>
		<br/>
		<h3 class="display-4"><strong>Comments:</strong></h3>
		<p>		<%= render @message.comments %>
		</p>

		</p>
	  </div>
	</div>
	<br/>
	<div class="card">
	  <div class="card-body">
	  	<h3>Reply To Message</h3>
		<%= render 'comments/form' %>

	<% if user_signed_in? %>
		<% if @message.user_id == current_user.id %>
			<%= link_to "Edit Message", edit_message_path, class: "btn btn-info"%>

			<%= button_to "Delete", @message ,method:'delete',class: "btn btn-danger",data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
		<% end %>
	<% end %>

	  </div>
	</div>


	
	<br/>
	<%= link_to "Back", root_path, class: "btn btn-secondary btn-outline"%>
	<br>
	<br>
	<br>


</div>
